dopenotes/account/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views
#from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'account'
urlpatterns = [
    # Accounts
    path('signup/', views.signup, name='account-signup'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', views.view_profile, name='view-profile'),
    path('profile/edit/', views.edit_profile, name='edit-profile'),
    # path('change_password/', views.account.change_password, name='change-password'),

    # # Password Reset
    # path('reset_password/', password_reset, {
    #     'template_name': 'accounts/reset_password.html',
    #     'post_reset_redirect': 'accounts:password_reset_done', 
    #     'email_template_name': 'accounts/reset_password_email.html'
    #     }, 
    #     name='reset-password'),

    # path('reset_password/done/', password_reset_done, {
    #     'template_name': 'accounts/reset_password_sent.html'
    #     },
    #     name='password_reset_done'),

    # re_path(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {
    #     'post_reset_redirect': 'accounts:password_reset_complete',
    #     'template_name': 'accounts/reset_password_new.html'
    #     }, 
    #     name='password_reset_confirm'),

    # path('reset_password/complete/', password_reset_complete, {
    #     'template_name': 'accounts/reset_password_complete.html'
    #     }, 
    #     name='password_reset_complete'),

    # # Add Details

]

dopenotes/dopenotes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', include('upload.urls')),
    path('account/', include('account.urls')),
    path('about/', views.index, name='about'),
    path('', views.index, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dopenotes/upload/urls.py
from django.urls import path
from django.conf.urls import url
#from django.contrib.auth.views import login, logout
from . import views

app_name = 'upload'
urlpatterns = [
    path('', views.index),
    path('class/create', views.create_class, name='create-class'),
    path('class/join', views.join_class, name='join-class'),
    url(r'^(?P<pk>\d+)/$', views.video_detail_view, name='detail')
]

dopenotes/upload/models.py
from django.db import models
from django.contrib.auth.models import User

class Video(models.Model):
    title = models.CharField(null=True, max_length=128)
    url = models.URLField('URL', max_length=2048, unique=True)
    keywords = models.TextField(null=True, max_length=None)
    transcription = models.TextField(null=True, max_length=None)
    resources = models.TextField(null=True, max_length=None)
    user = models.ForeignKey('account.UserProfile', on_delete=models.CASCADE, null=True)
    clazz = models.ForeignKey('Class', on_delete=models.CASCADE, null=True, verbose_name='Class', help_text='Register in classes in your user profile')
    text = models.TextField(null=True, max_length=None)
    extra_content = models.TextField(null=True, max_length=None)

    def __str__(self):
        return str(self.title)


class Class(models.Model):
    name = models.CharField(max_length=128)
    students = models.ManyToManyField('account.UserProfile')

    def __str__(self):
        return str(self.name)

dopenotes/upload/forms.py
from django import forms
from django.db import transaction
from upload.models import *
from django.forms import ModelForm

class UploadVideoForm(ModelForm):

    class Meta:
        model = Video
        fields = ['url', 'clazz']

class CreateClassForm(ModelForm):

    class Meta:
        model = Class
        fields = ['name']

class JoinClassForm(forms.Form):

    def get_classes():
        classes = []
        for clazz in Class.objects.all():
            classes.append((clazz.pk, str(clazz)))
        return classes

    classes = forms.MultipleChoiceField(choices=get_classes)

dopenotes/upload/templates/add_class_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
	<h1>Create a Class</h1>
	<h2>Name your class to begin note-taking!</h2>
	<br/>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-primary btn-sm" type="submit">Submit</button>
	</form>
	<br/>
</div>
{% endblock %}

dopenotes/upload/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'js/button.js' %}"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/about">About</a>
                    </li>
                </ul>
            </div>
            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="{% url 'home' %}">DopeNotes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/upload">Upload</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout' %}">Sign Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">Sign In</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <br />
        {% block head %}
            <title>Base</title>
        {% endblock %}
    </head>
    <body>
        {% block body %}

        {% endblock %}
    </body>
</html>

dopenotes/upload/templates/create_class_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
	<h1>Create a Class</h1>
	<h2>Name your class to begin note-taking!</h2>
	<br/>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-primary btn-sm" type="submit">Submit</button>
	</form>
	<br/>
</div>
{% endblock %}

dopenotes/upload/templates/detail_view.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>{{ video.title }}</h1>
    <h2> Key Phrases </h2>
    <ul>
        {% for phrase in phrases %}
          <li>{{ phrase }}</li>
        {% endfor %}
    </ul>

    <h2> Resources </p>
        {{ video.resources }}

    <h2> Transcription </h2>
    <p> {{ video.transcription }} </p>
</div>
{% endblock %}

dopenotes/upload/templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
</div>
{% endblock %}

dopenotes/upload/templates/join_class_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
	<h1>Join your classes</h1>
	<h2>Join your classes to begin note-taking!</h2>
	<br/>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-primary btn-sm" type="submit">Submit</button>
	</form>
	<br/>
	Class not listed? Create a class <a href="{% url 'upload:create-class' %}">here</a>.
</div>
{% endblock %}

dopenotes/upload/templates/upload_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
	<h1>Link Your Lecture!</h1>
	<h4>Paste the YouTube link to your video lecture here.</h4>
	<br>
	<!-- Search form -->
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-primary btn-sm" type="submit" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Transcribing...">Upload</button>
	</form>
	<br/>
</div>
{% endblock %}